server:
  port: 8001
spring:
  application:
    name: demoMybatis
  datasource:
      name: settle
      url: jdbc:mysql://10.100.75.135:3306/settle?useOldAliasMetadataBehavior=true&rewriteBatchedStatements=true&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      # 使用druid数据源  com.alibaba.druid.pool.DruidDataSource org.apache.commons.dbcp.BasicDataSource
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 400
      maxWait: 1000
      poolPreparedStatements: true
      defaultAutoCommit: true

mybatis:
  mapperLocations: classpath*:sqlmaps/*Mapper.xml
  typeAliasesPackage: com.demo.domain
  configLocation: classpath:mybatisConfig.xml


